### ISSUE TITLE
Add the remaining artefacts to this organiziation 

### ISSUE THREAD

**Issue by lindenthal** [pm2alliance/opm2-en#4]
The PM2 artefacts are already transformed to the asciidoc-format. The files are saved privately at the moment.

**Comment by iliask75** [comment]
It's going to be a long night.... but we are getting there

**Comment by ionut-ai** [comment]
The already transformed artefacts have been pushed to the master branch. We will continue to add them as we finalize the transformation for the others, avoiding a big push in the future.
